### ISSUE TITLE
在启动: Taro 配置有误，请检查！ 

### ISSUE THREAD

**Issue by code33** [SyMind/tarojs-plugin-svelte#4]
framework 的值 "svelte" 与任何指定选项 ["nerv","react","preact","solid","vue","vue3"] 都不匹配

**Comment by SyMind** [comment]
@code33 看起来是由于 Taro 的变更导致的，你愿意帮助解决这个问题么？

**Comment by code33** [comment]
那之前你的taro版本号是多少呐？

**Comment by SyMind** [comment]
@code33 `example` 中使用 `3.5.11`。

**Comment by code33** [comment]
OK 十分感谢

Cong-Cong Pan ***@***.***> 于2024年4月2日周二 12:40写道：
