### ISSUE TITLE
安装都OK了,现在是这个异常,请问是哪里出的问题? 感谢

### ISSUE THREAD

**Issue by code33** [SyMind/tarojs-plugin-svelte#5]
```
 if (isWebPlatform()) {
            ^

TypeError: isWebPlatform is not a function
```

![image](https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/0daeb7ed-f975-4cd3-a3b2-320fa88cd00b)

**Comment by code33** [comment]
贴上完整的截图
![image](https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/8bd8853d-faeb-4233-aebe-458ce53e4667)

**Comment by SyMind** [comment]
@code33 检查一下 `@tarojs/shared` 的版本。

**Comment by code33** [comment]
请问,得要哪个版本?

**Comment by SyMind** [comment]
3.5.11

**Comment by code33** [comment]
"@tarojs/taro": "3.5.11",
是这个版本

**Comment by SyMind** [comment]
看 `@tarojs/shared` 的版本，它可能被 lock 了。

**Comment by code33** [comment]
![image](https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/6e7617e5-4819-4792-836f-fb0892d30645)

**Comment by code33** [comment]
![image](https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/14725b33-5c26-421e-b436-279ee563514b)

**Comment by SyMind** [comment]
yarn list @tarojs/shared

**Comment by code33** [comment]
yarn list v1.22.22
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @tarojs/shared@3.5.11
Done in 0.55s.

![image](https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/0dcbf5eb-bcf9-4c78-a7e0-0b1d7a1f0a90)

**Comment by SyMind** [comment]
我看了截图，报错信息变了，看看 @tarojs/service 是什么版本？

**Comment by SyMind** [comment]
在 lock 文件中 check 一下，让 @tarojs/x 都保持在一个版本。

**Comment by code33** [comment]
```
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.5.11",
    "@tarojs/helper": "3.5.11",
    "@tarojs/plugin-framework-react": "3.5.11",
    "@tarojs/plugin-platform-alipay": "3.5.11",
    "@tarojs/plugin-platform-jd": "3.5.11",
    "@tarojs/plugin-platform-qq": "3.5.11",
    "@tarojs/plugin-platform-swan": "3.5.11",
    "@tarojs/plugin-platform-tt": "3.5.11",
    "@tarojs/plugin-platform-weapp": "3.5.11",
    "@tarojs/react": "3.5.11",
    "@tarojs/router": "3.5.11",
    "@tarojs/runtime": "3.5.11",
    "@tarojs/shared": "3.5.11",
    "@tarojs/taro": "3.5.11",
    "@tarojs/taro-h5": "3.5.11",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "tarojs-plugin-svelte": "^2.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.5.11",
    "@tarojs/webpack5-runner": "3.5.11",
    "@types/react": "^18.0.0",
    "@types/webpack-env": "^1.13.6",
    "babel-preset-taro": "3.5.11",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.5.11",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "react-refresh": "^0.11.0",
    "stylelint": "^14.4.0",
    "webpack": "5.69.0"
  }
```
![image](https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/c306c049-3785-46fd-9268-9901a1046327)

**Comment by code33** [comment]
木有这个包,
![image](https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/50ac19e0-36e5-4ccd-9738-712ce80f940f)

**Comment by SyMind** [comment]
这是一个间接依赖包。
________________________________
发件人: BunmJyo ***@***.***>
发送时间: Thursday, April 11, 2024 4:33:59 PM
收件人: SyMind/tarojs-plugin-svelte ***@***.***>
抄送: Cong-Cong Pan ***@***.***>; Comment ***@***.***>
主题: Re: [SyMind/tarojs-plugin-svelte] 安装都OK了,现在是这个异常,请问是哪里出的问题? 感谢 (Issue #5)


木有这个包,
image.png (view on web)<https://github.com/SyMind/tarojs-plugin-svelte/assets/3253255/50ac19e0-36e5-4ccd-9738-712ce80f940f>

―

**Comment by code33** [comment]
请问,能否提供一个 HelloWorld的项目 以供参考? 感谢

**Comment by SyMind** [comment]
`example` 目录下就是。
这里还有一个项目 https://github.com/SyMind/netease-cloud-music。
